### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by DerAndere1** [ellectroid/STM32F746-CMSIS-RCC-Max-Freq-SysTick-Basic-Timer-Demo#1]
Would be nice if you could provide a license for your demos. I would like to experiment with the code but without a license, I am not allowed to publish any source code that was derived from these examples. See here https://choosealicense.com/ for info.

Thanks for your consideration

**Comment by ellectroid** [comment]
There is no license, these are my own projects available to read to wider public. Some files inside are STMicroelectronics headers, they have licenses inside. Whatever is my piece of code, you're free to do whatever you want with it without any limitations at all, it's my gift to the world. At the end of the day, the intention was to make it clear for those who learns all of this (such as myself) to understand what things do and how they interact and how to set it all up. I'm not sure if writing to registers of timer can be licensed in any way. It's like licensing holding a phone at the ear. It's the only way to operate a microcontroller.

Anyway, whatever is my code, you're free to use it and/or modify it in any way possible.

**Comment by DerAndere1** [comment]
Thanks for clarifying your intentions. Note, however, that your code repository does not make those intentions clear, Currently, users have to find your "license" in your comment above.

The problem with code that does not come with a written license is described at https://choosealicense.com/no-permission/. Quote: 

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software.

Re:
>  It's the only way to operate a microcontroller.

But: you could have chosen a slightly different sequence of instructions or you could have used assembler language. There are good reasons to provide one of the [standard licenses](https://opensource.org/licenses/category). It would make it easier to combine your code with differently licensed code (e.g. via SPDX-License-Identifiers).
